[package]
name = "dom"
version = "0.0.1"
authors = ["rbpm <Wiesiek.Baranowski@gmail.com>"]

[dependencies]
quick-xml = "0.12"
failure = "0.1.1"

[workspace]
members = [
  "./",
  "examples/ex_dom",
]
